[package]
name = "progenitor"
description = "rule-based growth experiment with hexagonal cells"
version = "0.1.0"
authors = ["Martin Renold <martin@log2.ch>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/martinxyz/progenitor"

[lib]
name = "progenitor"
crate-type = ["rlib", "cdylib"]

[features]
default = ["console_error_panic_hook"]
python = ["pyo3", "numpy", "ndarray"]

[dependencies]
rand = "0.7"
rand_pcg = { version = "0.2", features = ["serde1"] }

# indexmap = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# hex2d = "0.2.0"  # wasm support currently only works with master
hex2d = { git = "https://github.com/dpc/hex2d-rs.git", rev = "2ffc1f8da994b4c8ce0ce9b6d8141942b4f48eed" }

wasm-bindgen = "0.2"
js-sys = "0.3"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pyo3 = { version = "0.11", optional = true, features = ["extension-module"] }
numpy = { version = "0.11", optional = true }
ndarray = { version = "0.13", optional = true }

[package.metadata.maturin]
requires-dist = ["numpy~=1.17"]

#[package.metadata.maturin.scripts]
#get_42 = "my_project:DummyClass.get_42"

# test this later, when doing optimizations:
#[profile.release]
#lto = "fat"
#codegen-units = 1
#debug = true

[profile.bench]
debug = true  # for better profiling

[package.metadata.wasm-pack.profile.release]
wasm-opt = false  # for whatever reason, wsam-opt bails out if I return String
