[package]
name = "progenitor"
description = "rule-based growth experiment with hexagonal cells"
version = "0.1.0"
authors = ["Martin Renold <martin@log2.ch>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/martinxyz/progenitor"

[lib]
name = "progenitor"
crate-type = ["rlib", "cdylib"]

[features]
default = ["console_error_panic_hook"]
python = ["pyo3", "numpy", "ndarray"]

[dependencies]
rand = "0.8"
rand_pcg = { version = "0.3", features = ["serde1"] }
getrandom = { version = "0.2", features = ["js"] }

# indexmap = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
hex2d = "1.1"

wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pyo3 = { version = "0.15", optional = true, features = ["extension-module"] }
numpy = { version = "0.15", optional = true }
ndarray = { version = "0.15", optional = true }

[package.metadata.maturin]
requires-dist = ["numpy~=1.17"]

#[package.metadata.maturin.scripts]
#get_42 = "my_project:DummyClass.get_42"

[profile.release]
lto = true  # ~30% .tick() speedup (most likely: inlining hex2d::Coordinate impl Neg)
            # ("fat" or "thin" both had the same effect)
codegen-units = 1  # ~40% .tick() speedup
panic = "abort"  # ~7% .tick() speedup
debug = 1  # no significant effect (less than 2%)
# opt-level = 3  # no significant effect (less than 2%)
# also: 9% speedup from 'export RUSTFLAGS="-C target-cpu=native"'
# overall 2x faster than "cargo release" without profile.release or RUSTFLAGS

[dev-dependencies]
rayon = "1.5"
# ndarray = "0.13"

[profile.bench]
debug = true  # for better profiling

[package.metadata.wasm-pack.profile.release]
wasm-opt = false  # for whatever reason, wsam-opt bails out if I return String
