[package]
name = "utils"
version = "0.0.0"
authors = ["Martin Renold <martin@log2.ch>"]
edition = "2024"
readme = "README.md"
license = "MIT"
repository = "https://github.com/martinxyz/progenitor"

[lib]
name = "utils"

[dependencies]
rayon = "1.5"
num_cpus = "1.13"
