[project]
name = "progenitor"
version = "0.0.0"
description = "progenitor native python extension"

dependencies = ["numpy>=1.22"]

[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[tool.maturin]
compatibility = "linux"
